// prisma/seed.js
const { PrismaClient } = require("@prisma/client");
const bcrypt = require("bcryptjs");

const prisma = new PrismaClient();

async function main() {
  // Seed Users
  const hashedPassword = await bcrypt.hash("12345678", 10);

  const users = [
    { firstName: "Sam", lastName: "thailanduk", email: "Samthailanduk122@gmail.com", role: "admin" },
    { firstName: "Michael", lastName: "Johnson", email: "michael.johnson@example.com", role: "provider" },
    { firstName: "Aisha", lastName: "Kamara", email: "aisha.kamara@example.com", role: "provider" },
    { firstName: "David", lastName: "Smith", email: "david.smith@example.com", role: "provider" },
    { firstName: "Kwame", lastName: "Mensah", email: "kwame.mensah@example.com", role: "provider" },
    { firstName: "Jennifer", lastName: "Brown", email: "jennifer.brown@example.com", role: "provider" },
    { firstName: "Samuel", lastName: "Osei", email: "samuel.osei@example.com", role: "provider" },
    { firstName: "Jessica", lastName: "Williams", email: "jessica.williams@example.com", role: "provider" },
    { firstName: "Ahmed", lastName: "Diallo", email: "ahmed.diallo@example.com", role: "provider" },
    { firstName: "Christopher", lastName: "Harris", email: "christopher.harris@example.com", role: "provider" },
    { firstName: "Fatima", lastName: "Abebe", email: "fatima.abebe@example.com", role: "provider" },
    { firstName: "Robert", lastName: "White", email: "robert.white@example.com", role: "provider" },
    { firstName: "Zainab", lastName: "Okafor", email: "zainab.okafor@example.com", role: "provider" },
    { firstName: "William", lastName: "Green", email: "william.green@example.com", role: "provider" },
    { firstName: "Oluwaseun", lastName: "Adebayo", email: "oluwaseun.adebayo@example.com", role: "provider" },
    { firstName: "Emily", lastName: "Thomas", email: "emily.thomas@example.com", role: "provider" },
  ].map((user) => ({
    ...user,
    password: hashedPassword,
    isActive: true,
  }));

  await prisma.users.createMany({
    data: users,
    skipDuplicates: true,
  });

  console.log("✅ Users seeded!");

  // Seed Jobs
  const jobs = [
    {
      id: "11111111-aaaa-47f6-b538-645b828e327e",
      title: "Furniture Delivery",
      category: "Van",
      notes: "Deliver sofa and chairs",
      status: "active",
      distance: 15,
      price: 2500,
      paymentTime: "7days",
      vanSize: "medium",
      movingItem: "Furniture",
      isHelpLoading: true,
      isTwoMenRequired: false,
      pickupPostCode: "E11",
      pickupAddressLine1: "Main Street 12",
      pickupAddressLine2: "Flat 2A",
      pickupCity: "London",
      pickupDate: new Date("2025-08-20T10:00:00"),
      isPickupTimeFlexible: true,
      isPickupASAP: false,
      dropOffPostCode: "E14",
      dropOffAddressLine1: "Market Road 5",
      dropOffAddressLine2: "Warehouse",
      dropOffCity: "London",
      dropOffDate: new Date("2025-08-20T13:00:00"),
      isDropOffTimeFlexible: true,
      isDropOffASAP: false,
      howManyItems: 5,
      documentsRequired: ["Signed Delivery Note"],
      documentsUploaded: [],
      createdAt: new Date("2025-08-16T10:00:00"),
      updatedAt: new Date("2025-08-16T10:05:00"),
    },
    {
      id: "22222222-bbbb-47f6-b538-645b828e327e",
      title: "Car Breakdown",
      category: "Recovery",
      notes: "Car stopped on highway",
      status: "active",
      distance: 35,
      price: 8000,
      paymentTime: "immediate",
      pickupPostCode: "LHR-22",
      pickupAddressLine1: "Motorway M2 KM45",
      pickupCity: "Lahore",
      pickupDate: new Date("2025-08-22T09:00:00"),
      isPickupTimeFlexible: false,
      isPickupASAP: true,
      dropOffPostCode: "LHR-11",
      dropOffAddressLine1: "Workshop Road",
      dropOffCity: "Lahore",
      dropOffDate: new Date("2025-08-22T11:00:00"),
      isDropOffTimeFlexible: false,
      isDropOffASAP: false,
      make: "Toyota",
      model: "Corolla",
      year: 2019,
      doesCarTurnOn: false,
      hasLogBook: true,
      hasCarKey: true,
      documentsRequired: ["Photo of Vehicle"],
      documentsUploaded: [],
      createdAt: new Date("2025-08-16T10:10:00"),
      updatedAt: new Date("2025-08-16T10:15:00"),
    },
    {
      id: "33333333-cccc-47f6-b538-645b828e327e",
      title: "House Removals",
      category: "Van",
      notes: "Moving entire house items",
      status: "active",
      distance: 50,
      price: 12000,
      paymentTime: "7days",
      vanSize: "large",
      movingItem: "Household",
      isHelpLoading: true,
      isTwoMenRequired: true,
      pickupPostCode: "BR1",
      pickupAddressLine1: "123 Kings Road",
      pickupCity: "Birmingham",
      pickupDate: new Date("2025-08-25T08:00:00"),
      isPickupTimeFlexible: false,
      isPickupASAP: false,
      dropOffPostCode: "BR2",
      dropOffAddressLine1: "456 Queens Avenue",
      dropOffCity: "Birmingham",
      dropOffDate: new Date("2025-08-25T17:00:00"),
      isDropOffTimeFlexible: false,
      isDropOffASAP: false,
      howManyItems: 50,
      documentsRequired: ["Signed Delivery Note", "Insurance Papers"],
      documentsUploaded: [],
      createdAt: new Date("2025-08-16T10:20:00"),
      updatedAt: new Date("2025-08-16T10:25:00"),
    },
    {
      id: "44444444-dddd-47f6-b538-645b828e327e",
      title: "Locksmith Emergency",
      category: "Locksmith",
      notes: "Locked out of apartment",
      status: "active",
      distance: 5,
      price: 3000,
      paymentTime: "immediate",
      pickupPostCode: "NY-1001",
      pickupAddressLine1: "5th Avenue",
      pickupCity: "New York",
      pickupDate: new Date("2025-08-17T19:00:00"),
      isPickupASAP: true,
      dropOffPostCode: "NY-1001",
      dropOffAddressLine1: "5th Avenue",
      dropOffCity: "New York",
      dropOffDate: new Date("2025-08-17T19:30:00"),
      isDropOffASAP: true,
      documentsRequired: ["ID Proof"],
      documentsUploaded: [],
      createdAt: new Date("2025-08-16T10:30:00"),
      updatedAt: new Date("2025-08-16T10:35:00"),
    },
    {
      id: "55555555-eeee-47f6-b538-645b828e327e",
      title: "Cleaning Service",
      category: "Cleaning",
      notes: "Deep cleaning required",
      status: "active",
      distance: 10,
      price: 5000,
      paymentTime: "7days",
      pickupPostCode: "LAX-55",
      pickupAddressLine1: "Sunset Blvd",
      pickupCity: "Los Angeles",
      pickupDate: new Date("2025-08-19T09:00:00"),
      dropOffPostCode: "LAX-55",
      dropOffAddressLine1: "Sunset Blvd",
      dropOffCity: "Los Angeles",
      dropOffDate: new Date("2025-08-19T15:00:00"),
      documentsRequired: ["Work Order"],
      documentsUploaded: [],
      createdAt: new Date("2025-08-16T10:40:00"),
      updatedAt: new Date("2025-08-16T10:45:00"),
    },
    {
      id: "66666666-ffff-47f6-b538-645b828e327e",
      title: "Document Delivery",
      category: "Courier",
      notes: "Deliver confidential papers",
      status: "active",
      distance: 20,
      price: 1500,
      paymentTime: "immediate",
      pickupPostCode: "DXB-09",
      pickupAddressLine1: "Business Bay",
      pickupCity: "Dubai",
      pickupDate: new Date("2025-08-18T11:00:00"),
      isPickupASAP: false,
      dropOffPostCode: "DXB-15",
      dropOffAddressLine1: "Sheikh Zayed Road",
      dropOffCity: "Dubai",
      dropOffDate: new Date("2025-08-18T12:00:00"),
      isDropOffASAP: false,
      documentsRequired: ["Receipt"],
      documentsUploaded: [],
      createdAt: new Date("2025-08-16T10:50:00"),
      updatedAt: new Date("2025-08-16T10:55:00"),
    },
    {
      id: "77777777-gggg-47f6-b538-645b828e327e",
      title: "Pet Transport",
      category: "Van",
      notes: "Move pets safely",
      status: "active",
      distance: 25,
      price: 4000,
      paymentTime: "7days",
      vanSize: "small",
      movingItem: "Pets",
      pickupPostCode: "TOR-77",
      pickupAddressLine1: "Bay Street",
      pickupCity: "Toronto",
      pickupDate: new Date("2025-08-23T14:00:00"),
      dropOffPostCode: "TOR-88",
      dropOffAddressLine1: "Yonge Street",
      dropOffCity: "Toronto",
      dropOffDate: new Date("2025-08-23T16:00:00"),
      documentsRequired: ["Vet Certificate"],
      documentsUploaded: [],
      createdAt: new Date("2025-08-16T11:00:00"),
      updatedAt: new Date("2025-08-16T11:05:00"),
    },
    {
      id: "88888888-hhhh-47f6-b538-645b828e327e",
      title: "Medical Transport",
      category: "Courier",
      notes: "Urgent blood delivery",
      status: "active",
      distance: 8,
      price: 6000,
      paymentTime: "immediate",
      pickupPostCode: "KHI-01",
      pickupAddressLine1: "Hospital Road",
      pickupCity: "Karachi",
      pickupDate: new Date("2025-08-17T08:00:00"),
      isPickupASAP: true,
      dropOffPostCode: "KHI-02",
      dropOffAddressLine1: "Lab Street",
      dropOffCity: "Karachi",
      dropOffDate: new Date("2025-08-17T08:30:00"),
      isDropOffASAP: true,
      documentsRequired: ["Doctor’s Letter"],
      documentsUploaded: [],
      createdAt: new Date("2025-08-16T11:10:00"),
      updatedAt: new Date("2025-08-16T11:15:00"),
    },
    {
      id: "99999999-iiii-47f6-b538-645b828e327e",
      title: "Event Setup",
      category: "Van",
      notes: "Deliver and setup stage",
      status: "active",
      distance: 40,
      price: 10000,
      paymentTime: "7days",
      vanSize: "large",
      movingItem: "Stage Equipment",
      pickupPostCode: "BER-33",
      pickupAddressLine1: "Alexanderplatz",
      pickupCity: "Berlin",
      pickupDate: new Date("2025-08-24T07:00:00"),
      dropOffPostCode: "BER-40",
      dropOffAddressLine1: "Brandenburg Gate",
      dropOffCity: "Berlin",
      dropOffDate: new Date("2025-08-24T12:00:00"),
      documentsRequired: ["Work Permit"],
      documentsUploaded: [],
      createdAt: new Date("2025-08-16T11:20:00"),
      updatedAt: new Date("2025-08-16T11:25:00"),
    },
    {
      id: "10101010-jjjj-47f6-b538-645b828e327e",
      title: "Office Relocation",
      category: "Van",
      notes: "Move office equipment",
      status: "active",
      distance: 30,
      price: 15000,
      paymentTime: "7days",
      vanSize: "extra-large",
      movingItem: "Office",
      isTwoMenRequired: true,
      pickupPostCode: "ISB-10",
      pickupAddressLine1: "Blue Area",
      pickupCity: "Islamabad",
      pickupDate: new Date("2025-08-30T09:00:00"),
      dropOffPostCode: "ISB-20",
      dropOffAddressLine1: "G-11 Markaz",
      dropOffCity: "Islamabad",
      dropOffDate: new Date("2025-08-30T18:00:00"),
      documentsRequired: ["NOC", "Work Order"],
      documentsUploaded: [],
      createdAt: new Date("2025-08-16T11:30:00"),
      updatedAt: new Date("2025-08-16T11:35:00"),
    },
  ];

  await prisma.jobs.createMany({
    data: jobs,
    skipDuplicates: true,
  });

  console.log("✅ Jobs seeded!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
