export const getInvitationEmailTemplate = (name, invitationLink, role, inviterName) => {
  const roleDisplayName = {
    affiliate: "Affiliate",
    provider: "Service Provider",
    restaurant: "Restaurant Owner",
    "shop-owner": "Shop Owner"
  };

  const roleName = roleDisplayName[role] || role;
  const isAffiliateInvite = role === "affiliate";

  const benefitsHtml = isAffiliateInvite
    ? `
      ✅ <strong>Affiliate Access</strong> - Onboard shops and restaurants to the platform<br />
      ✅ <strong>Order-Based Earnings</strong> - Earn commission from order transactions generated by your onboarded businesses<br />
      ✅ <strong>Performance Focus</strong> - Earnings are tied to business activity, not signups or subscriptions
    `
    : `
      ✅ <strong>2 Months Free Trial</strong> - Start using all features immediately at no cost<br />
      ✅ <strong>Full Access</strong> - All platform features available during your trial<br />
      ✅ <strong>No Credit Card Required</strong> - Set up your account and start right away
    `;

  const roleSpecificText = isAffiliateInvite
    ? `
    <p style="font-size:14px;color:#0e0e0e;padding-top:16px;">
      Your affiliate commissions are calculated from order transactions generated by businesses you onboard.
      You do not earn commission from account signups or subscriptions.
    </p>
    `
    : `
    <p style="font-size:14px;color:#0e0e0e;padding-top:16px;">
      After your trial period, your account access will continue based on platform policy and approval.
    </p>
    `;

  return `
    <p style="font-size:20px;color:#0e0e0e;"> Hi <b>${name},</b></p>

    <p style="font-size:14px;color:#0e0e0e;padding-top:16px;">
      You've been invited by <strong>${inviterName}</strong> to join <strong>Swipped</strong> as a <strong>${roleName}</strong>!
    </p>

    <p style="font-size:14px;color:#0e0e0e;padding-top:16px;">
      <strong>Great news!</strong> As part of your invitation, you'll receive:
    </p>

    <p style="font-size:14px;color:#0e0e0e;">
      ${benefitsHtml}
    </p>

    ${roleSpecificText}

    <p style="font-size:14px;color:#0e0e0e;padding-top:16px;">
      <strong>Ready to get started?</strong>
    </p>

    <p style="font-size:14px;color:#0e0e0e;">
      Click the link below to set up your password and get started:
    </p>

    <p style="text-align:center;padding-top:16px;">
      <a href="${invitationLink}" style="background-color:#0052cc;color:white;padding:12px 20px;border-radius:4px;text-decoration:none;">
        Set Up Your Password
      </a>
    </p>

    <p style="font-size:14px;color:#0e0e0e;padding-top:16px;">
      This invitation link will expire in 7 days. If you need a new link, please contact ${inviterName} or our support team.
    </p>

    <p style="font-size:14px;color:#0e0e0e;padding-top:16px;">
      Have questions? Our support team is here to help! Just reply to this email or reach out to ${process.env.NEXT_PUBLIC_SUPPORT_EMAIL}.
    </p>

    <p style="font-size:14px;color:#0e0e0e;padding-top:16px;">
      Welcome to Swipped!<br />
      The Swipped Team
    </p>
  `;
};

